AWSTemplateFormatVersion: 2010-09-09
Description: >-
  grid-front

Transform:
  - AWS::Serverless-2016-10-31

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: grid-connect-challenge.name
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['',['arn:aws:s3:::', !Ref WebsiteBucket,/*]]

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: grid-connect-challenge.name
      DomainValidationOptions:
          - DomainName: grid-connect-challenge.name
            ValidationDomain: grid-connect-challenge.name
      ValidationMethod: DNS

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Select [1, !Split ["//", !GetAtt WebsiteBucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultRootObject: index.html
        HttpVersion: http2
        Enabled: true
        Aliases: 
        - grid-connect-challenge.name
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  ARecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: grid-connect-challenge.name.
      RecordSets:
      - Name: grid-connect-challenge.name.
        Type: A
        AliasTarget:
          DNSName: !GetAtt Distribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2

